version: '3'

services:
  database:
    networks:
      - dev
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
  application:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    volumes:
      - ./:/workspace:z
    ports:
      - '3000:3000'
    restart: on-failure
    networks:
      - dev
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: appdb
      DB_SYNCHRONIZE: 'true'
networks:
  dev:
    name: dev
